fuzz-config: add config to support fuzzing test
thesofproject/kconfig pull request #57
Opened 2021-06-25 09:00 UTC by libinyang

kernel config for fuzzing test.

Signed-off-by: Libin Yang <libin.yang@intel.com>

2021-06-25 15:28 UTC, plbossart requested changes
Thanks @libinyang 

No objection to adding this fragment, but I'd like to minimize it what's not already defined by the defconfig+base. Can you try and optimize a bit?

Also the memory debug is already defined, maybe with too many options. Maybe we can split in memory-debug-base and memory-debug-extensive fragments.

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_DEBUG_FS=y
already set by default.

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_NAMESPACES=y
already set by default

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_USER_NS=y
already set by default

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_UTS_NS=y
already set by default

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_NET_NS=y
all above already set

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_DEBUG_VM=y
we already have the memory-debug defconfig. Do we need to redefine this here?

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_PSTORE=m
move one line up, this gates all the others below.

2021-06-25 15:28 UTC, plbossart commented on fuzz-defconfig
> +CONFIG_PSTORE_BLK_CONSOLE_SIZE=64
missing end of line.

2021-06-28 06:13 UTC, libinyang commented
@plbossart Thanks for reviewing. I have removed all the duplicated definitions and suggest reusing other defconfigs in the README. For the memory-debug-defconfig, I think it should be OK. Fuzz config is copied from syzkaller suggestion of minimum configuration. And I believe applying all configs in memory-debug-defconfig is acceptable for fuzzing test.

2021-06-28 15:14 UTC, merged