base-defconfig: enable coretemp sensor driver
thesofproject/kconfig pull request #72
Opened 2022-06-08 03:00 UTC by aiChaoSONG

This module can be used on UP Xtreme board to
monitor core temperature, enable it to reduce
the onboard fan noise.

Signed-off-by: Chao Song <chao.song@linux.intel.com>

After enable the kernel kconfig, use the utility here for fan speed auto-control: https://downloads.up-community.org/download/upx-tgl01-fan-control-linux/

2022-06-08 03:26 UTC, greg-intel approved these changes

2022-06-08 13:04 UTC, plbossart requested changes

2022-06-08 13:04 UTC, plbossart commented on base-defconfig
> +# Core temperatature sensor
typo: temperature

2022-06-09 02:11 UTC, aiChaoSONG commented
@plbossart I think the target users are developers who has an UpExtreme i11 board on their desk. In the lab, we have devices that are much more noisy than UpExtreme board, and also no one really works always in the lab.

2022-06-09 12:39 UTC, plbossart approved these changes

2022-06-09 12:39 UTC, merged